Page({
  data:{
    weeklyMovieList:[
    {
      name:"教父",
      comment:"最精彩的剧本，最真实的黑帮电影。",
      imagePath:"/images/image2.png",
      isHighlyRecommended:true,
      id:1291841
    },
    {
      name:"这个杀手不太冷",
      comment:"小萝莉与怪蜀黍纯真的爱情故事。",
      imagePath:"/images/image2.png",
      isHighlyRecommended:false,
      id:78
    },
    ],
    currentIndex:0
  },
  onLoad:function(options){
    this.setData({
      currentIndex:this.data.weeklyMovieList.length-1
    })
  },
  f0:function(event){
    this.setData({
      currentIndex:this.data.weeklyMovieList.length-1
    })
  },
  f1:function(event){
    var movieId=event.currentTarget.dataset.movieId
    console.log(movieId);
    wx.navigateTo({
      url: '/pages/detail/detail?id='+movieId,
    })
  },
  onShareAppMessage:function(){
    return{
      title:"每周推荐"
    }
  }
})